version: 1
runtime: python27
api_version: 1
threadsafe: true
application: item-tracker

handlers:
- url: /static/css
  static_dir: static/css
- url: /static/js
  static_dir: static/js
- url: /static/font
  static_dir: static/font
- url: /_ah/spi/.*
  script: item_tracker_api.app
- url: /jobs/.*
  script: cron_jobs.cronApp
  login: admin
- url : /admin/create
  script: admin_config.app
  login: admin
- url: /.*
  secure: always
  script: item_tracker.app

libraries:
- name: webapp2
  version: latest
- name: pycrypto
  version: "2.6"
- name: endpoints
  version: 1.0
- name: jinja2
  version: latest
